name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    timeout-minutes: 180
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install the project
        run: |
          uv sync --all-extras --dev
          uv pip install -e "."
      - name: "Activate the project"
        run: source .venv/bin/activate
      - name: "Install Jupyter Kernel"
        run: uv run -m ipykernel install --user --name=anl2025
      - name: "Run pytest for ${{ matrix.python-version }}"
        run: "uv run pytest src/anl2025 tests || uv run pytest --last-failed src/anl2025 tests"
